### PR TITLE
added the compliance state to the status compare

### PR DESCRIPTION
**Pull request by gparvin**
Signed-off-by: Gus Parvin <gparvin@redhat.com>
Working on issue https://github.com/open-cluster-management/backlog/issues/14615
The compare didn't have the compliance state in the new status so always failed.

### CODE REVIEW

**Comment by gparvin** [comment]
/hold
investigate test failure

**Comment by ycao56** [comment]
@gparvin Can you add more details? I am not sure I understand the problem.

**Comment by gparvin** [comment]
@ycao56 The problem is the compare always returned false.  The oldStatus contained the entries:
- complianceState
- details
But the newStatus only contains
- details

I tried adding the complianceState to the newStatus but I hit some test failures and that's why the details are now checked separately from the compliancestate.

**Review by ycao56 — APPROVED** [review]

**Pull request merged**
